### ISSUE TITLE
DTW not working?

### ISSUE THREAD

**Issue by nielsr2** [Interactml/iml-unity#5] opened 2021-11-19 12:03 UTC
Hi

I've been trying to use InteractML with Dynamic Time Warping - But I can't even get the example scene to work.

It is not stated anywhere which 'gestures' it is by default trained on, but training a new gesture (like a simple semi-circle, at same approx. position) does not appear to work either. 

I'm using Unity 2019.4.29f1.

Furthermore, I think there's a mistake in the [wiki - 7. Import a Script into an InteractML Graph and Pull Data from Graph](https://github.com/Interactml/iml-unity/wiki/7.-Import-a-Script-into-an-InteractML-Graph-and-Pull-Data-from-Graph) 

[PullFromIMLGraph]
public float SetLightIntensity;

Should it not be PullFromIMLController?

**Comment by carlotes247** [comment] 2021-11-19 14:32
Hi!

I think the problem is that you are using a very old version of the plugin. The releases page is outdated (we had quite a hectic time until now and we haven't uploaded a new release yet). The attribute on the wiki is correct since we changed the vocabulary from IMLController to IMLGraph.

Try downloading the master branch and see if the examples work well for you that way.

**Comment by nielsr2** [comment] 2021-11-23 10:03
Hi! 

Thank you very much for the swift reply. You're right - That is most likely the issue. I'll be trying it out later.

Thank you for the work on this promising tool.

**Comment by carlotes247** [comment] 2021-11-23 11:27
No worries! I have updated the installation instructions. Let me know if the master branch works well on your computer to close this issue.

By the way, what are you thinking using InteractML for? We are trying to collect some information on how people are using the tool :)

**Comment by nielsr2** [comment] 2021-11-25 09:29
I couldn't get the Mouse_Input_color_Output_DTW example to work right off the bat - This time it was however on a windows 7 computer ( was macos and win 10 the other times) , but we unfortunately don't have time to investigate it further. So you can just close the issue.

We're using it for EMG to detect basic actions such as a grasp for smart home control. We'll however be using Wekinator - "Delete all recordings" as the only option for DTW example control is unfortunately a dealbreaker. But it is very nice to see this tool being worked on, will definitely be using it in the future.

**Comment by carlotes247** [comment] 2021-12-02 11:49
Thanks for the feedback! I will take that into account for the next release to try and implement at least a "Delete last recording" into the ML nodes. Closing this issue now

**Closed as completed by carlotes247** 2021-12-02 11:49 UTC
